version: "3"

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_ROOT_PASSWORD: db_password
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - database_data:/var/lib/mysql:rw
    ports:
      - "3306:3306"

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###
